apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smoelenboek-adapter.fullname" . }}
  labels:
    {{- include "smoelenboek-adapter.labels" . | nindent 4 }}
type: Opaque
stringData:
  Entra__TenantId: {{ .Values.entra.tenantId | quote }}
  Entra__ClientId: {{ .Values.entra.clientId | quote }}
  Entra__ClientSecret: {{ .Values.entra.clientSecret | quote }}
  OpenObjects__Token: {{ .Values.openObjects.token | quote }}
