apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpdc-adapter.fullname" . }}
  labels:
    {{- include "openpdc-adapter.labels" . | nindent 4 }}
type: Opaque
stringData:
  OpenObjects__Token: {{ .Values.openObjects.token | quote }}
