<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1848</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenPdc.Client\OpenPdc.Client.csproj" />
    <ProjectReference Include="..\..\Shared\OpenObjects.Client\OpenObjects.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
  </ItemGroup>

</Project>
